version: '3'
services:
  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: example
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password

  web:
    build:
      context: .
    ports:
      - '8090:5000'
    depends_on:
      - db
    secrets:
      - db-password

secrets:
  db-password:
    file: ./db-password.txt
